version: '3'
services:
  nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos-standalone
    environment:
      - MODE=standalone
      - PREFER_HOST_NAME=localhost
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./data/nacos:/home/nacos/data
    networks:
      - nacos-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8848/nacos/v1/console/health/readiness" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  nacos-network:
    driver: bridge
